FROM node:18

ARG BUILD_BASE_PATH

# Install necessary build tools
RUN apt-get update && apt-get install -y python3 make g++ openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /data

COPY $BUILD_BASE_PATH/package.json  .

RUN npm install

COPY $BUILD_BASE_PATH/ .

CMD [ "npm", "start" ]
