FROM node:18

ARG BUILD_BASE_PATH

# Install necessary build tools if needed (node:18 already has most of them)

WORKDIR /data

COPY $BUILD_BASE_PATH/package.json  .

RUN npm install

COPY $BUILD_BASE_PATH/ .

CMD [ "npm", "start" ]
