apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history-service
  namespace: ecommerce
  labels:
    app: order-history-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-history-service
  template:
    metadata:
      labels:
        app: order-history-service
    spec:
      containers:
        - name: order-history-service
          image: hgyang25/order-history-service:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          env:
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://10.0.30.65:30417"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: SERVICE_NAME
              value: "order-history-service"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-history-service
  namespace: ecommerce
spec:
  selector:
    app: order-history-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP


