apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # API Gateway
  API_GATEWAY_PORT: '3000'

  # Service ports
  ORDERS_SERVICE_PORT: '3001'
  ORDER_HISTORY_SERVICE_PORT: '3002'
  PRODUCTS_SERVICE_PORT: '3003'
  PAYMENTS_SERVICE_PORT: '3004'
  DIGITAL_IDENTITY_SERVICE_PORT: '3005'
  PROFILE_SERVICE_PORT: '3006'

  # Service origins (K8s internal DNS)
  ORDERS_SERVICE_CONTAINER_ORIGIN: 'http://orders-service'
  ORDER_HISTORY_SERVICE_CONTAINER_ORIGIN: 'http://order-history-service'
  PRODUCTS_SERVICE_CONTAINER_ORIGIN: 'http://products-service'
  PAYMENTS_SERVICE_CONTAINER_ORIGIN: 'http://payments-service'
  DIGITAL_IDENTITY_SERVICE_CONTAINER_ORIGIN: 'http://digital-identity-service'
  PROFILE_SERVICE_CONTAINER_ORIGIN: 'http://profile-service'


  # CDN
  CDN_PORT: '8080'
  CDN_HOST: 'cdn'

  # Frontend
  FRONTEND_CLIENT_PORT: '4200'
  API_GATEWAY_URI: 'http://api-gateway:3000'
  # IMPORTANT: Update this to your actual production domain
  NEXT_PUBLIC_API_GATEWAY_URI: 'https://api.redis-shopping.ntdevopsmlflow.io.vn'

  # Log level
  LOG_LEVEL: 'info'
