apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: ecommerce
  labels:
    app: orders-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: hgyang25/orders-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          env:
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://10.0.30.65:30417"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
                value: "grpc"
              - name: OTEL_SERVICE_NAME
                value: "orders-service"
              - name: SERVICE_NAME
              value: "orders-service"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
                            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: ecommerce
spec:
  selector:
    app: orders-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP




