name: Database Restore

on:
  workflow_dispatch:
    inputs:
      backup_file_name:
        description: 'Tên file backup trên S3 (VD: 2026-09-12_02-00-00/mongodb.archive.gz)'
        required: true
        type: string

jobs:
  restore-mongodb:
    name: Restore MongoDB
    runs-on: self-hosted
    steps:
      - name: Download MongoDB tools
        run: |
          wget -q https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.4.tgz
          tar -zxvf mongodb-database-tools-ubuntu2204-x86_64-100.9.4.tgz
          echo "${PWD}/mongodb-database-tools-ubuntu2204-x86_64-100.9.4/bin" >> $GITHUB_PATH

      - name: Configure CMC S3 Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> "$GITHUB_ENV"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> "$GITHUB_ENV"
          echo "AWS_DEFAULT_REGION=ap-southeast-1" >> "$GITHUB_ENV"

      - name: Download backup from S3
        run: |
          mkdir -p backups
          aws s3 cp \
            s3://${{ secrets.S3_BACKUP_BUCKET }}/mongodb/${{ github.event.inputs.backup_file_name }} \
            backups/mongodb.archive.gz \
            --endpoint-url=${{ secrets.S3_ENDPOINT }}

      - name: Restore MongoDB database
        run: |
          echo "Starting MongoDB restore..."

          mongorestore \
            --uri="mongodb://admin:rootpassword@${{ secrets.MONGO_IP }}:27017/dbFashion" \
            --gzip \
            --archive="backups/mongodb.archive.gz" \
            --drop

          echo "MongoDB restore completed."
